git

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,26 +1,30 @@
 #!/usr/bin/env bash
+# Transfers a file from Holberton's client to another.
+#
+#  Accepts four parameters only:
+#     The path to the file to be transferred.
+#     The IP of the server to transfer the file to.
+#     The username that scp connects with.
+#     The path to the SSH private key that scp uses.
 
-# Check if all 4 parameters are provided
-if [ "$#" -ne 4 ]; then
-    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-    exit 1
+if [ $# -lt 4 ]
+then
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
 fi
+# assigning parameters to variables
 
-# Assign parameters to variables
-PATH_TO_FILE="$1"
-IP="$2"
-USERNAME="$3"
-PATH_TO_SSH_KEY="$4"
+PATH_TO_FILE=$1
+IP=$2
+USERNAME=$3
+PATH_TO_SSH_KEY=$4
 
-# Disable strict host key checking for scp
-SSH_OPTIONS="-o StrictHostKeyChecking=no"
+scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
 
-# Use scp to transfer the file to the user's home directory on the server
-scp $SSH_OPTIONS -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"
-
-# Check the exit status of scp
-if [ $? -eq 0 ]; then
-    echo "File transfer successful!"
+# checking for transfer status
+#  this is not part of the task — jx optional
+if [ $? -eq 0 ]
+then
+	echo "Transfer Scuccesfull"
 else
-    echo "File transfer failed."
+	echo "Transfee error, Try again"
 fi
